# Generated by Django 3.2.8 on 2021-11-29 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_mark_the_time_fech'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.CharField(default='Hola, twitter', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mark_the_time',
            name='fech',
            field=models.DateField(default=datetime.date(2021, 11, 29)),
        ),
    ]
